// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDirDy1JblzZI87D6nwrj9NoPYKg_nXXA',
    appId: '1:557343289723:web:63feb3f124a8a101564dde',
    messagingSenderId: '557343289723',
    projectId: 'chat-app-migara',
    authDomain: 'chat-app-migara.firebaseapp.com',
    storageBucket: 'chat-app-migara.appspot.com',
    measurementId: 'G-CX75S6786G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANOy9qqRtHPUOGxr9cDsju1sCn79uAEHs',
    appId: '1:557343289723:android:203bcf89ad9fa79a564dde',
    messagingSenderId: '557343289723',
    projectId: 'chat-app-migara',
    storageBucket: 'chat-app-migara.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBukfJ7CanDed7fkstMK9QbaEKNfYSxwLA',
    appId: '1:557343289723:ios:014aeb3b8b458dd3564dde',
    messagingSenderId: '557343289723',
    projectId: 'chat-app-migara',
    storageBucket: 'chat-app-migara.appspot.com',
    iosBundleId: 'lk.migara.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBukfJ7CanDed7fkstMK9QbaEKNfYSxwLA',
    appId: '1:557343289723:ios:d1bfaf494c0a280f564dde',
    messagingSenderId: '557343289723',
    projectId: 'chat-app-migara',
    storageBucket: 'chat-app-migara.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDirDy1JblzZI87D6nwrj9NoPYKg_nXXA',
    appId: '1:557343289723:web:d6806623a5aa0eab564dde',
    messagingSenderId: '557343289723',
    projectId: 'chat-app-migara',
    authDomain: 'chat-app-migara.firebaseapp.com',
    storageBucket: 'chat-app-migara.appspot.com',
    measurementId: 'G-0V31CECH3N',
  );
}
